### ISSUE TITLE
not working with mysql?

### ISSUE THREAD

**Issue by ajoslin103** [taviroquai/db2graphql#5]
given this connection to my local mysql database

```
{
  "client": "mysql",
  "version": "5.7.1",
  "debug": true,
  "connection": {
    "host": "127.0.0.1",
    "user": "root",
    "password": "omitted",
    "database": "adonis_graphql_server"
  },
  "exclude": []
}
```

with this node 

```
const knex = require('knex');
const db2g = require('db2graphql');
const conn = knex(require('./connection.json'));
const api = new db2g('demo', conn);
api.connect().then(() => {
  const schema = api.getSchema();
  console.log(schema);
  conn.destroy();
});

```

the debug output shows it's reaching for 'public' (schema?) when I expected to reach for my specified database "adonis_graphql_server"

$ node index.js
```
{ method: 'raw',
  sql:
   '\n      SELECT table_name as name \n      FROM information_schema.tables \n      WHERE table_schema = ?\n      \n    ',
  bindings: [ 'public' ],
  options: {},
  __knexQueryUid: 'd5372950-4525-11ea-9dff-adbef368f885' }
type Query {
  getAPIName: String
}

input Condition {
  sql: String!
  val: [String!]!
}

```

**Comment by ajoslin103** [comment]
I've created a pull-request  #6  with the solution I used for myself

**Comment by taviroquai** [comment]
Hi, thank you for using db2graphql! :)

I just found that it is not well documented but the correct way to connect to mysql is like the example:
https://github.com/taviroquai/db2graphql/blob/9daf217ab5c48e1b21d27ee2d1ecade1a1293d6d/demo_mysql/index.js#L10

Basically, you have to supply the **database name** in the **connect method**.

Please try it without your pull request because it is the right way to do it.

Thanks again!

**Comment by taviroquai** [comment]
Hi, README was updated to explain how to connect to Mysql database.

**Comment by taviroquai** [comment]
Closing for now. But still open for discussion.
